### ISSUE TITLE
Last character in clock is missing

### ISSUE THREAD

**Issue by ozo2003** [b3by/atom-clock#20]
![screenshot_2017-03-01_13-27-57](https://cloud.githubusercontent.com/assets/5328929/23458013/f47e3494-fe82-11e6-836c-25b6e5cc908e.png)

When Atom is launched, clock doesn't display last character. If I go to settings and change format, it goes normal for a while but goes back to missing last character.

Atom: 1.15.4 x64
Electron: 1.3.13
OS: XUbuntu 16.04
Thrown From: atom-clock package 0.1.5

**Comment by b3by** [comment]
Thank you for the issue. I will look into it as soon as possible, maybe trying to replicate it.
May I ask you which packages are currently active in your environment? I'm guessing it might depend on some external package that somehow interacts with the status bar.

**Comment by eduncan911** [comment]
FYI, I have been noticing this too over the last few days.

OS: macOS 10.12.3
Atom: 1.14.4 x64
atom-clock: 0.1.5

<img width="634" alt="screen shot 2017-03-01 at 9 10 41 am" src="https://cloud.githubusercontent.com/assets/104980/23463354/1eb9b568-fe5f-11e6-88fe-6ba8df6718aa.png">

Note that it occurs regardless of what file, plugin or additional "status bar" items.  If I start with a blank editor, it is still truncated:

<img width="855" alt="screen shot 2017-03-01 at 9 13 14 am" src="https://cloud.githubusercontent.com/assets/104980/23463405/553d207a-fe5f-11e6-9cd0-849c22fe86ce.png">

I do have a custom Time Format in the settings: `MM/DD h:mma`  But this does not matter.  If I remove the custom Time Format and restart Atom, it is still truncating the "time":

<img width="573" alt="screen shot 2017-03-01 at 9 14 59 am" src="https://cloud.githubusercontent.com/assets/104980/23463468/96e95674-fe5f-11e6-81a2-59831a0cc315.png">

--

I've noticed a few things that temporarily fixes it for the session that Atom is running: 

* Disable/Enable the plugin.
* Remove/Add or Tweak the "Time Format" settings to anything. 

Doing either of these immediately fixes the SPAN or DIV issue that is occurring.  

--

You can "scroll" left to right the statusbar in this area.

--

Lastly, I do use a custom Font with custom editor stylesheets.  Since Atom 1.13 (aka "Deprecation Hell" upgrade), a lot of styles had to be changed.  

I'm wondering if the way the statusbar is calculating the width is now different - so when you go and populate the div/span, it isn't resized accordingly.

**Comment by b3by** [comment]
Thanks for the detailed showcase of the bug.
In the latest release of the clock, I just changed the way the packages displays the clock in the bar, because the div containing the time moves slightly if also seconds are displayed. Right now, I recalculate the width of the clock content every time the format changes, then I add some extra pixels for safety and I keep it fixed. I'm wondering, probably something is wrong when the package initializes and calculates the size for the first time.

I'll look into the issue ASAP, thank you again for letting me know!

**Comment by b3by** [comment]
I was able to reproduce the bug in some situations where the developer console is placed to the right side of the screen. I applied a relative position to the container, now it seems to work properly (at least, I was not able to reproduce the bug any longer). I will update the package version, hoping that's it!

**Comment by eduncan911** [comment]
@b3by it works! 👍 

Though, the vertical alignment is a tad off.  🥇 

So.. close...!

<img width="798" alt="screen shot 2017-03-05 at 1 42 37 pm" src="https://cloud.githubusercontent.com/assets/104980/23590196/bce3cf1a-01a9-11e7-9a68-fff19528cf15.png">

**Comment by b3by** [comment]
Oh no!
I aligned the clock in the vertical middle, just like the other tiles out of the box, because on my system it was vertically off, just a bit.
I'm thinking, this might depend to the font you're using. I could get the vertical size of the status bar and place the clock right in the middle... oh, this is just for positioning a tiny text cell :(
