### ISSUE TITLE
FEATURE REQUEST: Add fuzzy clock to atom-clock

### ISSUE THREAD

**Issue by sluedecke** [b3by/atom-clock#5]
FEATURE REQUEST

I am using the fuzzy clock on my Linux machine and like it a lot.  It displays time depending on a configured level of fuzziness as: 'Ten to twelve' or 'noon' or 'middle of the week'.  Prior work incl. translations can be found here (MIT licensed):

https://github.com/m66n/fuzzyclock

It would be a nice addition to atom-clock :)

**Comment by b3by** [comment]
It seems like a nice feature, still I think it might be a little bit stretched. Writing the time in such a fuzzy way cuts out the locale facets, thus making it enjoyable in English only (I decided to use `moment` so that the time formatting would have left completely to the user).
I'm still considering it, maybe with a separate package tough.
