### ISSUE TITLE
Add possibility to copy time into clipboard

### ISSUE THREAD

**Issue by SirUli** [b3by/atom-clock#66]
Hi @b3by,

would you consider adding a "copy" feature for the time?

Use-Case is that i'm using Atom for blogging and i would need to add the current time as a creation date. Easy would be if i could just click on the time and it would be in the clipboard. 

Thanks for your time!

Best Regards, Uli

**Comment by b3by** [comment]
Thank you for submitting this issue! It is actually a good idea, I can probably silently incorporate it into the current version of the package so that the time will be copied into the clipboard. I will keep you posted on this one, see if it is doable shortly!

**Comment by SirUli** [comment]
@b3by did you maybe have time to look into this? Thanks in advance!

**Comment by b3by** [comment]
Oh man, I am so sorry, I completely forgot about this as writing my thesis is sucking out almost all of my time. Given my current quarantine tho, I promise I'll work on this, and see if it can be delivered within the week!

**Comment by SirUli** [comment]
Absolutely no worries ;) Thanks for taking it into consideration :)

Cheers!

**Comment by b3by** [comment]
So, the feature should be currently working in the latest package version (0.1.18). Right now I am using the tooltip format, that is copied into the clipboard as a plain string. A dismissable notification is displayed when the time is successfully copied.

Given all these years since I last worked on this project, I hope I didn't break anything. I will give this  few more days so that users can update the package, so any feedback on the feature is highly appreciated!

And of course, thank you for the original idea and for your patience!

**Comment by SirUli** [comment]
Super duper :) Works and totally helps my case. Thanks again!
