### ISSUE TITLE
customizing

### ISSUE THREAD

**Issue by psychoticgamer19** [b3by/atom-clock#67]
it will not work please fix it

**Comment by ftm** [comment]
Would you be able to be more specific?

**Comment by psychoticgamer19** [comment]
i tried the code and it didnt work

**Comment by ftm** [comment]
If you are genuinely experiencing an issue then we will need more information to be able to help. For example an error message and stack trace as well as details such as your OS, Atom version, and version of the `atom-clock` package you are using.

**Comment by b3by** [comment]
I second @ftm on this. If there is a bug in the code, we need more information in order to find it and fix it.

- Do you get any error notification or console message that points to a package malfunction?
- What OS are you on?
- Which Atom version are you running?
- Did you try starting Atom in safe mode, and later activating the package?
- How did you install the package?

**Comment by b3by** [comment]
As this didn't receive updates, I will close it for now. Thank you @ftm for still looking into these issues!
